// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Channel represents an IRC channel
 * State: OPEN (dialog open, may or may not be joined), JOINED (dialog open and joined), CLOSED (dialog closed, not joined)
 */
export class Channel {
    /**
     * Creates a new Channel instance.
     * @param {Partial<Channel>} [$$source = {}] - The source object to create the Channel.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("network_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["network_id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("topic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["topic"] = "";
        }
        if (!("modes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modes"] = "";
        }
        if (!("auto_join" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_join"] = false;
        }
        if (!("is_open" in $$source)) {
            /**
             * Dialog/pane is open (OPEN or JOINED state)
             * @member
             * @type {boolean}
             */
            this["is_open"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Channel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Channel}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Channel(/** @type {Partial<Channel>} */($$parsedSource));
    }
}

/**
 * ChannelUser represents a user in a channel
 */
export class ChannelUser {
    /**
     * Creates a new ChannelUser instance.
     * @param {Partial<ChannelUser>} [$$source = {}] - The source object to create the ChannelUser.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("channel_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["channel_id"] = 0;
        }
        if (!("nickname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nickname"] = "";
        }
        if (!("modes" in $$source)) {
            /**
             * e.g., "@" for op, "+" for voice
             * @member
             * @type {string}
             */
            this["modes"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelUser instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChannelUser}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelUser(/** @type {Partial<ChannelUser>} */($$parsedSource));
    }
}

/**
 * Message represents an IRC message
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("network_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["network_id"] = 0;
        }
        if (!("channel_id" in $$source)) {
            /**
             * Nullable for private messages
             * @member
             * @type {number | null}
             */
            this["channel_id"] = null;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("message_type" in $$source)) {
            /**
             * 'privmsg', 'notice', 'action', etc.
             * @member
             * @type {string}
             */
            this["message_type"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("raw_line" in $$source)) {
            /**
             * Original IRC line
             * @member
             * @type {string}
             */
            this["raw_line"] = "";
        }
        if (!("pm_target" in $$source)) {
            /**
             * Conversation peer for PMs ("" for channel/status/server rows)
             * @member
             * @type {string}
             */
            this["pm_target"] = "";
        }
        if (!("msgid" in $$source)) {
            /**
             * IRCv3 message id ("" for legacy/local rows); dedup key for CHATHISTORY
             * @member
             * @type {string}
             */
            this["msgid"] = "";
        }
        if (!("reply_msgid" in $$source)) {
            /**
             * IRCv3 +draft/reply: msgid of the parent message ("" if not a reply)
             * @member
             * @type {string}
             */
            this["reply_msgid"] = "";
        }
        if (!("channel_context" in $$source)) {
            /**
             * IRCv3 +draft/channel-context: channel a PM is about ("" otherwise)
             * @member
             * @type {string}
             */
            this["channel_context"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * Network represents an IRC network configuration
 */
export class Network {
    /**
     * Creates a new Network instance.
     * @param {Partial<Network>} [$$source = {}] - The source object to create the Network.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * Deprecated: use Servers
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * Deprecated: use Servers
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("tls" in $$source)) {
            /**
             * Deprecated: use Servers
             * @member
             * @type {boolean}
             */
            this["tls"] = false;
        }
        if (!("nickname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nickname"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("realname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["realname"] = "";
        }
        if (!("sasl_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sasl_enabled"] = false;
        }
        if (!("sasl_mechanism" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["sasl_mechanism"] = null;
        }
        if (!("sasl_username" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["sasl_username"] = null;
        }
        if (!("sasl_external_cert" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["sasl_external_cert"] = null;
        }
        if (!("auto_connect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_connect"] = false;
        }
        if (!("identify_as_bot" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["identify_as_bot"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }
        if (!("hasPassword" in $$source)) {
            /**
             * Computed, non-persisted flags populated by the App layer for the frontend.
             * Has* report whether a secret is set (keychain or fallback column) without
             * exposing the value; CredentialStorageInsecure is true when any secret is
             * currently held in a plaintext column rather than the keychain.
             * @member
             * @type {boolean}
             */
            this["hasPassword"] = false;
        }
        if (!("hasSaslPassword" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasSaslPassword"] = false;
        }
        if (!("credentialStorageInsecure" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["credentialStorageInsecure"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Network instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Network}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Network(/** @type {Partial<Network>} */($$parsedSource));
    }
}

/**
 * PinnedMessage represents a message that has been pinned, with pin metadata
 */
export class PinnedMessage {
    /**
     * Creates a new PinnedMessage instance.
     * @param {Partial<PinnedMessage>} [$$source = {}] - The source object to create the PinnedMessage.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("network_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["network_id"] = 0;
        }
        if (!("channel_id" in $$source)) {
            /**
             * Nullable for private messages
             * @member
             * @type {number | null}
             */
            this["channel_id"] = null;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("message_type" in $$source)) {
            /**
             * 'privmsg', 'notice', 'action', etc.
             * @member
             * @type {string}
             */
            this["message_type"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("raw_line" in $$source)) {
            /**
             * Original IRC line
             * @member
             * @type {string}
             */
            this["raw_line"] = "";
        }
        if (!("pm_target" in $$source)) {
            /**
             * Conversation peer for PMs ("" for channel/status/server rows)
             * @member
             * @type {string}
             */
            this["pm_target"] = "";
        }
        if (!("msgid" in $$source)) {
            /**
             * IRCv3 message id ("" for legacy/local rows); dedup key for CHATHISTORY
             * @member
             * @type {string}
             */
            this["msgid"] = "";
        }
        if (!("reply_msgid" in $$source)) {
            /**
             * IRCv3 +draft/reply: msgid of the parent message ("" if not a reply)
             * @member
             * @type {string}
             */
            this["reply_msgid"] = "";
        }
        if (!("channel_context" in $$source)) {
            /**
             * IRCv3 +draft/channel-context: channel a PM is about ("" otherwise)
             * @member
             * @type {string}
             */
            this["channel_context"] = "";
        }
        if (!("pinned_by" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pinned_by"] = "";
        }
        if (!("pinned_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["pinned_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PinnedMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PinnedMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PinnedMessage(/** @type {Partial<PinnedMessage>} */($$parsedSource));
    }
}

/**
 * STSPolicy is a persisted IRCv3 STS (Strict Transport Security) policy: a host
 * the client has learned (over TLS) must always be reached via TLS on Port until
 * ExpiresAt. Keyed by hostname, UA-wide. ExpiresAt is unix seconds.
 */
export class STSPolicy {
    /**
     * Creates a new STSPolicy instance.
     * @param {Partial<STSPolicy>} [$$source = {}] - The source object to create the STSPolicy.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("expires_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expires_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new STSPolicy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {STSPolicy}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new STSPolicy(/** @type {Partial<STSPolicy>} */($$parsedSource));
    }
}

/**
 * SearchResult extends Message with additional context for search results
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("network_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["network_id"] = 0;
        }
        if (!("channel_id" in $$source)) {
            /**
             * Nullable for private messages
             * @member
             * @type {number | null}
             */
            this["channel_id"] = null;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("message_type" in $$source)) {
            /**
             * 'privmsg', 'notice', 'action', etc.
             * @member
             * @type {string}
             */
            this["message_type"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("raw_line" in $$source)) {
            /**
             * Original IRC line
             * @member
             * @type {string}
             */
            this["raw_line"] = "";
        }
        if (!("pm_target" in $$source)) {
            /**
             * Conversation peer for PMs ("" for channel/status/server rows)
             * @member
             * @type {string}
             */
            this["pm_target"] = "";
        }
        if (!("msgid" in $$source)) {
            /**
             * IRCv3 message id ("" for legacy/local rows); dedup key for CHATHISTORY
             * @member
             * @type {string}
             */
            this["msgid"] = "";
        }
        if (!("reply_msgid" in $$source)) {
            /**
             * IRCv3 +draft/reply: msgid of the parent message ("" if not a reply)
             * @member
             * @type {string}
             */
            this["reply_msgid"] = "";
        }
        if (!("channel_context" in $$source)) {
            /**
             * IRCv3 +draft/channel-context: channel a PM is about ("" otherwise)
             * @member
             * @type {string}
             */
            this["channel_context"] = "";
        }
        if (!("channel_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["channel_name"] = "";
        }
        if (!("network_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["network_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

/**
 * Server represents a single server address within a network
 */
export class Server {
    /**
     * Creates a new Server instance.
     * @param {Partial<Server>} [$$source = {}] - The source object to create the Server.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("network_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["network_id"] = 0;
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("tls" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tls"] = false;
        }
        if (!("order" in $$source)) {
            /**
             * Order for fallback (lower = higher priority)
             * @member
             * @type {number}
             */
            this["order"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Server instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Server}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Server(/** @type {Partial<Server>} */($$parsedSource));
    }
}
