// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ConnectionMode controls how an outgoing direct connection is negotiated.
 * @readonly
 * @enum {string}
 */
export const ConnectionMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ConnectionAutomatic: "automatic",
    ConnectionClassic: "classic",
    ConnectionPassive: "passive",
};

/**
 * Direction identifies which side owns the file being transferred.
 * @readonly
 * @enum {string}
 */
export const Direction = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DirectionIncoming: "incoming",
    DirectionOutgoing: "outgoing",
};

/**
 * HistoryRetention is deliberately string-valued at the Wails boundary.
 * @readonly
 * @enum {string}
 */
export const HistoryRetention = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    HistoryForever: "forever",
    History30Days: "30_days",
    HistoryNone: "none",
};

/**
 * Settings are the validated direct-file-transfer preferences.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("downloadDirectory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadDirectory"] = "";
        }
        if (!("historyRetention" in $$source)) {
            /**
             * @member
             * @type {HistoryRetention}
             */
            this["historyRetention"] = HistoryRetention.$zero;
        }
        if (!("connectionMode" in $$source)) {
            /**
             * @member
             * @type {ConnectionMode}
             */
            this["connectionMode"] = ConnectionMode.$zero;
        }
        if (!("advertisedAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["advertisedAddress"] = "";
        }
        if (!("portMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["portMin"] = 0;
        }
        if (!("portMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["portMax"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * Status is the user-visible lifecycle state for a file transfer.
 * @readonly
 * @enum {string}
 */
export const Status = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusOffered: "offered",
    StatusQueued: "queued",
    StatusNegotiating: "negotiating",
    StatusConnecting: "connecting",
    StatusTransferring: "transferring",
    StatusCompleted: "completed",
    StatusFailed: "failed",
    StatusCanceled: "canceled",
    StatusDeclined: "declined",
    StatusResumable: "resumable",
};

/**
 * View is the safe, typed model sent to React.
 */
export class View {
    /**
     * Creates a new View instance.
     * @param {Partial<View>} [$$source = {}] - The source object to create the View.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("networkId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["networkId"] = 0;
        }
        if (!("networkName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["networkName"] = "";
        }
        if (!("peer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["peer"] = "";
        }
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {Direction}
             */
            this["direction"] = Direction.$zero;
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("transferredBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["transferredBytes"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = Status.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["completedAt"] = undefined;
        }
        if (!("speedBps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speedBps"] = 0;
        }
        if (!("etaSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["etaSeconds"] = 0;
        }
        if (!("fileAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fileAvailable"] = false;
        }
        if (!("resumable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["resumable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new View instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {View}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new View(/** @type {Partial<View>} */($$parsedSource));
    }
}
