// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Event represents a generic event
 */
export class Event {
    /**
     * Creates a new Event instance.
     * @param {Partial<Event>} [$$source = {}] - The source object to create the Event.
     */
    constructor($$source = {}) {
        if (!("Type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Type"] = "";
        }
        if (!("Data" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["Data"] = {};
        }
        if (!("Timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["Timestamp"] = null;
        }
        if (!("Source" in $$source)) {
            /**
             * @member
             * @type {EventSource}
             */
            this["Source"] = EventSource.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Event}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Data" in $$parsedSource) {
            $$parsedSource["Data"] = $$createField1_0($$parsedSource["Data"]);
        }
        return new Event(/** @type {Partial<Event>} */($$parsedSource));
    }
}

/**
 * EventSource represents the source of an event
 * @readonly
 * @enum {string}
 */
export const EventSource = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    EventSourceIRC: "irc",

    /**
     * Future
     */
    EventSourceUI: "ui",
    EventSourceSystem: "system",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
