// Code generated by 'yaegi extract github.com/matt0x6f/irc-client/cascade'. DO NOT EDIT.

package syms

import (
	"github.com/matt0x6f/irc-client/cascade"
	"reflect"
)

func init() {
	Symbols["github.com/matt0x6f/irc-client/cascade/cascade"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewClient":                reflect.ValueOf(cascade.NewClient),
		"NewJoinEvent":             reflect.ValueOf(cascade.NewJoinEvent),
		"NewKickEvent":             reflect.ValueOf(cascade.NewKickEvent),
		"NewNickEvent":             reflect.ValueOf(cascade.NewNickEvent),
		"NewNoticeEvent":           reflect.ValueOf(cascade.NewNoticeEvent),
		"NewNoticeEventWithDirect": reflect.ValueOf(cascade.NewNoticeEventWithDirect),
		"NewPartEvent":             reflect.ValueOf(cascade.NewPartEvent),
		"NewQuitEvent":             reflect.ValueOf(cascade.NewQuitEvent),
		"NewTextEvent":             reflect.ValueOf(cascade.NewTextEvent),
		"NewTextEventWithDirect":   reflect.ValueOf(cascade.NewTextEventWithDirect),
		"NewTime":                  reflect.ValueOf(cascade.NewTime),
		"NewUserStatusEvent":       reflect.ValueOf(cascade.NewUserStatusEvent),
		"WithIRCActions":           reflect.ValueOf(cascade.WithIRCActions),
		"WithNetworkQueries":       reflect.ValueOf(cascade.WithNetworkQueries),

		// type definitions
		"Client":          reflect.ValueOf((*cascade.Client)(nil)),
		"ClientOption":    reflect.ValueOf((*cascade.ClientOption)(nil)),
		"JoinEvent":       reflect.ValueOf((*cascade.JoinEvent)(nil)),
		"KickEvent":       reflect.ValueOf((*cascade.KickEvent)(nil)),
		"Network":         reflect.ValueOf((*cascade.Network)(nil)),
		"NickEvent":       reflect.ValueOf((*cascade.NickEvent)(nil)),
		"NoticeEvent":     reflect.ValueOf((*cascade.NoticeEvent)(nil)),
		"PartEvent":       reflect.ValueOf((*cascade.PartEvent)(nil)),
		"QuitEvent":       reflect.ValueOf((*cascade.QuitEvent)(nil)),
		"TextEvent":       reflect.ValueOf((*cascade.TextEvent)(nil)),
		"Time":            reflect.ValueOf((*cascade.Time)(nil)),
		"User":            reflect.ValueOf((*cascade.User)(nil)),
		"UserStatus":      reflect.ValueOf((*cascade.UserStatus)(nil)),
		"UserStatusEvent": reflect.ValueOf((*cascade.UserStatusEvent)(nil)),
	}
}
