// Code generated by 'yaegi extract github.com/matt0x6f/irc-client/internal/script/cascade'. DO NOT EDIT.

package syms

import (
	"github.com/matt0x6f/irc-client/internal/script/cascade"
	"reflect"
)

func init() {
	Symbols["github.com/matt0x6f/irc-client/internal/script/cascade/cascade"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewTextEvent": reflect.ValueOf(cascade.NewTextEvent),

		// type definitions
		"TextEvent": reflect.ValueOf((*cascade.TextEvent)(nil)),
	}
}
