// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "./internal/events/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as irc$0 from "./internal/irc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./internal/storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddMonitor adds a nick to the network's durable buddy list and, if connected,
 * asks the server to track it (MONITOR +). It persists even when offline, so the
 * nick is (re-)sent on the next connect.
 * @param {number} networkID
 * @param {string} nick
 * @returns {$CancellablePromise<void>}
 */
export function AddMonitor(networkID, nick) {
    return $Call.ByID(3992658754, networkID, nick);
}

/**
 * CheckForUpdates is the Wails-bound manual update trigger, called from the
 * "Check for Updates…" menu item and the About-pane button. On a dev build the
 * updater was never configured (see isReleaseVersion in main.go); rather than
 * silently doing nothing, we emit updater:unavailable so the frontend can toast
 * a friendly explanation. Otherwise CheckAndInstall opens the framework's themed
 * updater window, checks GitHub, and downloads/verifies/stages a newer release
 * if one exists. A manual check intentionally always shows the window (including
 * the reassuring "You're Up to Date" state).
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdates() {
    return $Call.ByID(2675659504);
}

/**
 * ClearPaneFocus clears focus from a pane and emits an event
 * @param {number} networkID
 * @param {string} paneType
 * @param {string} paneName
 * @returns {$CancellablePromise<void>}
 */
export function ClearPaneFocus(networkID, paneType, paneName) {
    return $Call.ByID(1854039756, networkID, paneType, paneName);
}

/**
 * ClearSTSPolicy removes the STS policy for a host. This is a deliberate security
 * downgrade (the next connection to that host may go plaintext again) exposed for
 * recovery/testing; the frontend gates it behind a confirmation. It broadcasts a
 * sts-policy event so any open window refreshes its badge.
 * @param {string} hostname
 * @returns {$CancellablePromise<void>}
 */
export function ClearSTSPolicy(hostname) {
    return $Call.ByID(2005130476, hostname);
}

/**
 * ConnectNetwork connects to an IRC network (fresh connect, e.g. user-initiated
 * or startup auto-connect). Reconnect after an unexpected drop goes through
 * connectNetwork with reconnect=true so the client rejoins its whole session.
 * @param {$models.NetworkConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function ConnectNetwork(config) {
    return $Call.ByID(1245530049, config);
}

/**
 * DeleteNetwork deletes a network configuration
 * @param {number} networkID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNetwork(networkID) {
    return $Call.ByID(1276456224, networkID);
}

/**
 * DisablePlugin disables a plugin
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DisablePlugin(name) {
    return $Call.ByID(4075667952, name);
}

/**
 * DisconnectNetwork disconnects from a network
 * @param {number} networkID
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectNetwork(networkID) {
    return $Call.ByID(1238325307, networkID);
}

/**
 * EnablePlugin enables a plugin
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function EnablePlugin(name) {
    return $Call.ByID(3947152785, name);
}

/**
 * GetBuildInfo returns the version, commit, and build date stamped into the
 * binary at link time.
 * @returns {$CancellablePromise<$models.BuildInfo>}
 */
export function GetBuildInfo() {
    return $Call.ByID(3168473285).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCachedChannelList returns the last-fetched LIST result for a network, if any.
 * It never triggers a fetch — callers use RequestChannelList to force a refresh.
 * @param {number} networkID
 * @returns {$CancellablePromise<$models.ChannelListCacheResult>}
 */
export function GetCachedChannelList(networkID) {
    return $Call.ByID(2256754220, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetChannelIDByName retrieves a channel ID by network ID and channel name
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<number | null>}
 */
export function GetChannelIDByName(networkID, channelName) {
    return $Call.ByID(1310009965, networkID, channelName);
}

/**
 * GetChannelInfo retrieves channel information including topic and users
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<$models.ChannelInfo | null>}
 */
export function GetChannelInfo(networkID, channelName) {
    return $Call.ByID(3499926414, networkID, channelName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetChannels retrieves channels for a network
 * @param {number} networkID
 * @returns {$CancellablePromise<storage$0.Channel[]>}
 */
export function GetChannels(networkID) {
    return $Call.ByID(1369558439, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetCommands returns metadata for every known command (built-in here; merged
 * with plugin commands in Phase 4). Bound to the frontend via Wails.
 * @returns {$CancellablePromise<$models.CommandInfo[]>}
 */
export function GetCommands() {
    return $Call.ByID(983453965).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetConnectionStatus returns whether a network is connected
 * @param {number} networkID
 * @returns {$CancellablePromise<boolean>}
 */
export function GetConnectionStatus(networkID) {
    return $Call.ByID(1041368369, networkID);
}

/**
 * GetCurrentNick returns the nick the server currently knows us by on a network,
 * which can differ from the configured nick while a nick collision is being
 * resolved. Returns an empty string when the network has no active client.
 * @param {number} networkID
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentNick(networkID) {
    return $Call.ByID(869658591, networkID);
}

/**
 * GetDefaultLogPath returns the default log file location, for use as a UI
 * placeholder when the user hasn't chosen a custom path.
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultLogPath() {
    return $Call.ByID(3647489945);
}

/**
 * GetJoinedChannels retrieves channels where the current user is still a member
 * @param {number} networkID
 * @returns {$CancellablePromise<storage$0.Channel[]>}
 */
export function GetJoinedChannels(networkID) {
    return $Call.ByID(209386014, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetLastOpenPane retrieves the most recently updated open channel or PM conversation
 * @returns {$CancellablePromise<$models.LastOpenPane | null>}
 */
export function GetLastOpenPane() {
    return $Call.ByID(1367469045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetLogConfig returns the current file-logging configuration, with defaults
 * applied for any unset values.
 * @returns {$CancellablePromise<$models.LogConfig>}
 */
export function GetLogConfig() {
    return $Call.ByID(3565499149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetMessages retrieves messages for a network and channel
 * @param {number} networkID
 * @param {number | null} channelID
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessages(networkID, channelID, limit) {
    return $Call.ByID(3832618599, networkID, channelID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetMessagesAfter retrieves up to `limit` messages newer than afterID (exclusive),
 * chronological order. Used to scroll forward out of an anchored context window.
 * @param {number} networkID
 * @param {number | null} channelID
 * @param {number} afterID
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessagesAfter(networkID, channelID, afterID, limit) {
    return $Call.ByID(4016273103, networkID, channelID, afterID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetMessagesAround retrieves a window of messages around a target message id,
 * so the frontend can "jump" to a pinned message with surrounding context.
 * @param {number} networkID
 * @param {number | null} channelID
 * @param {number} targetID
 * @param {number} window
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessagesAround(networkID, channelID, targetID, window) {
    return $Call.ByID(468669170, networkID, channelID, targetID, window).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetMessagesBefore retrieves up to `limit` messages older than beforeID (exclusive),
 * chronological order. Used for scrollback pagination. channelID nil = status pane.
 * @param {number} networkID
 * @param {number | null} channelID
 * @param {number} beforeID
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessagesBefore(networkID, channelID, beforeID, limit) {
    return $Call.ByID(2291548608, networkID, channelID, beforeID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetMessagesBeforeTime retrieves up to `limit` messages older than `beforeISO`
 * (an ISO8601/RFC3339 timestamp) by server-time, chronological order. Unlike
 * GetMessagesBefore (id-keyed), this surfaces CHATHISTORY-backfilled rows (high
 * id, old timestamp). A non-empty pmTarget selects a PM conversation; otherwise
 * channelID selects a channel (nil = status pane). Used for unified local + server
 * scrollback pagination.
 * 
 * The cursor is a string (not time.Time) deliberately: a time.Time parameter in a
 * Wails-bound method makes the binding generator emit a time.Time class for every
 * timestamp field, which breaks `new Date(msg.timestamp)` across the frontend.
 * @param {number} networkID
 * @param {number | null} channelID
 * @param {string} pmTarget
 * @param {string} beforeISO
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessagesBeforeTime(networkID, channelID, pmTarget, beforeISO, limit) {
    return $Call.ByID(1921588377, networkID, channelID, pmTarget, beforeISO, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetMonitorList returns the network's durable MONITOR buddy list joined with each
 * nick's current online state (unknown until the first 730/731, defaulting offline).
 * @param {number} networkID
 * @returns {$CancellablePromise<$models.MonitorEntry[]>}
 */
export function GetMonitorList(networkID) {
    return $Call.ByID(3280037895, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetNetworkBots returns the lowercased nicks recognized as IRCv3 bots for a
 * network this session. The frontend calls this to hydrate its bot set when a
 * window opens or reloads; live additions arrive via the "bot-event" event.
 * Returns an empty slice when the network is not currently connected.
 * @param {number} networkID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetNetworkBots(networkID) {
    return $Call.ByID(1037950925, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetNetworkUserMeta returns the live roster attributes (away/account/host) for
 * a network this session, keyed by lowercased nick. The frontend calls this to
 * hydrate its roster metadata when a window opens or reloads; live changes
 * arrive via the "usermeta-event" event. Returns an empty map when the network
 * is not currently connected.
 * @param {number} networkID
 * @returns {$CancellablePromise<{ [_ in string]?: irc$0.UserMeta }>}
 */
export function GetNetworkUserMeta(networkID) {
    return $Call.ByID(1426666641, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetNetworks retrieves all networks
 * @returns {$CancellablePromise<storage$0.Network[]>}
 */
export function GetNetworks() {
    return $Call.ByID(366685148).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetNicknameColor gets color for a single nickname
 * @param {number} networkID
 * @param {string} nickname
 * @returns {$CancellablePromise<string>}
 */
export function GetNicknameColor(networkID, nickname) {
    return $Call.ByID(2930834622, networkID, nickname);
}

/**
 * GetNicknameColorsBatch gets colors for multiple nicknames efficiently
 * @param {number} networkID
 * @param {string[]} nicknames
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetNicknameColorsBatch(networkID, nicknames) {
    return $Call.ByID(4229567593, networkID, nicknames).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetOpenChannels retrieves channels where the dialog is open or the user is joined
 * @param {number} networkID
 * @returns {$CancellablePromise<storage$0.Channel[]>}
 */
export function GetOpenChannels(networkID) {
    return $Call.ByID(564233579, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetPinnedMessages retrieves pinned messages for a network and channel
 * @param {number} networkID
 * @param {number | null} channelID
 * @returns {$CancellablePromise<storage$0.PinnedMessage[]>}
 */
export function GetPinnedMessages(networkID, channelID) {
    return $Call.ByID(380870585, networkID, channelID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetPluginConfig gets the configuration for a plugin
 * @param {string} pluginName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetPluginConfig(pluginName) {
    return $Call.ByID(1436487730, pluginName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetPluginConfigSchema gets the configuration schema for a plugin
 * @param {string} pluginName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetPluginConfigSchema(pluginName) {
    return $Call.ByID(249168125, pluginName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetPrivateMessageConversations retrieves a list of users with private message conversations
 * @param {number} networkID
 * @param {boolean} openOnly
 * @returns {$CancellablePromise<string[]>}
 */
export function GetPrivateMessageConversations(networkID, openOnly) {
    return $Call.ByID(839521643, networkID, openOnly).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetPrivateMessages retrieves private messages for a network and user
 * @param {number} networkID
 * @param {string} targetUser
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetPrivateMessages(networkID, targetUser, limit) {
    return $Call.ByID(2750786118, networkID, targetUser, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetSTSPolicies returns every stored IRCv3 STS policy (host → enforced TLS port +
 * expiry), for the settings panel to render an "enforced until" badge per server.
 * @returns {$CancellablePromise<storage$0.STSPolicy[]>}
 */
export function GetSTSPolicies() {
    return $Call.ByID(3662233731).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * GetServerCapabilities retrieves server capabilities from ISUPPORT for a network
 * @param {number} networkID
 * @returns {$CancellablePromise<$models.ServerCapabilitiesInfo | null>}
 */
export function GetServerCapabilities(networkID) {
    return $Call.ByID(1639110850, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetServers retrieves server addresses for a network
 * @param {number} networkID
 * @returns {$CancellablePromise<storage$0.Server[]>}
 */
export function GetServers(networkID) {
    return $Call.ByID(4270553301, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * GetSetting returns a persisted UI/app preference by key. A missing key
 * returns an empty string (not an error) so the frontend can apply its default.
 * Used for preferences like theme mode and accent that can't live in the
 * WKWebView's localStorage because macOS drops it between launches.
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetSetting(key) {
    return $Call.ByID(48053349, key);
}

/**
 * Greet returns a greeting for the given name (kept for compatibility)
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(2659711170, name);
}

/**
 * LeaveChannel leaves an IRC channel
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<void>}
 */
export function LeaveChannel(networkID, channelName) {
    return $Call.ByID(2303728547, networkID, channelName);
}

/**
 * ListPlugins returns information about all plugins
 * @returns {$CancellablePromise<$models.PluginInfo[]>}
 */
export function ListPlugins() {
    return $Call.ByID(3314730135).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * OnEvent implements the events.Subscriber interface to forward events to frontend
 * @param {events$0.Event} event
 * @returns {$CancellablePromise<void>}
 */
export function OnEvent(event) {
    return $Call.ByID(844865600, event);
}

/**
 * OpenSettings opens (or focuses) the standalone Settings window.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(2024983644);
}

/**
 * OpenSettingsAbout opens the Settings window to the about section.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettingsAbout() {
    return $Call.ByID(2440832785);
}

/**
 * OpenSettingsDisplay opens the Settings window to the display section.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettingsDisplay() {
    return $Call.ByID(2211152578);
}

/**
 * OpenSettingsNetworks opens the Settings window to the networks section.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettingsNetworks() {
    return $Call.ByID(1081996467);
}

/**
 * OpenSettingsPlugins opens the Settings window to the plugins section.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettingsPlugins() {
    return $Call.ByID(2435594228);
}

/**
 * PinMessage pins a message in a network/channel (channelID nil for status/PM panes)
 * @param {number} networkID
 * @param {number} messageID
 * @param {number | null} channelID
 * @returns {$CancellablePromise<void>}
 */
export function PinMessage(networkID, messageID, channelID) {
    return $Call.ByID(1631361803, networkID, messageID, channelID);
}

/**
 * PrintLocalLines writes client-local system lines (e.g. /help output) into a
 * buffer through the normal message pipeline so they render and scroll like
 * other system notices. target: "" or "status" => status buffer; "#name" =>
 * channel; otherwise a PM peer nick.
 * @param {number} networkID
 * @param {string} target
 * @param {string[]} lines
 * @returns {$CancellablePromise<void>}
 */
export function PrintLocalLines(networkID, target, lines) {
    return $Call.ByID(821357734, networkID, target, lines);
}

/**
 * ReloadPlugin reloads a plugin
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ReloadPlugin(name) {
    return $Call.ByID(2644883255, name);
}

/**
 * RemoveMonitor removes a nick from the buddy list and stops tracking it.
 * @param {number} networkID
 * @param {string} nick
 * @returns {$CancellablePromise<void>}
 */
export function RemoveMonitor(networkID, nick) {
    return $Call.ByID(2238775289, networkID, nick);
}

/**
 * RequestChannelBans asks the server for a channel's ban list. The result is delivered
 * asynchronously to the frontend via the "channel.banlist" event.
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<void>}
 */
export function RequestChannelBans(networkID, channelName) {
    return $Call.ByID(2034965975, networkID, channelName);
}

/**
 * RequestChannelList sends the LIST command to request available channels from the server
 * @param {number} networkID
 * @returns {$CancellablePromise<void>}
 */
export function RequestChannelList(networkID) {
    return $Call.ByID(2678000793, networkID);
}

/**
 * RequestChatHistoryBefore asks the server to replay up to `limit` messages older
 * than beforeISO (an ISO8601 timestamp) for target. Used by scroll-to-top deep
 * backscroll once the local store is exhausted.
 * @param {number} networkID
 * @param {string} target
 * @param {string} beforeISO
 * @param {number} limit
 * @returns {$CancellablePromise<void>}
 */
export function RequestChatHistoryBefore(networkID, target, beforeISO, limit) {
    return $Call.ByID(3507479247, networkID, target, beforeISO, limit);
}

/**
 * RequestChatHistoryLatest asks the server to replay the most recent `limit`
 * messages for target (channel name or PM nick). Used for on-open catch-up of a
 * PM/query pane (channel catch-up fires automatically on JOIN). Replays are stored
 * and deduped by msgid; the frontend learns of them via the "history-event".
 * @param {number} networkID
 * @param {string} target
 * @param {number} limit
 * @returns {$CancellablePromise<void>}
 */
export function RequestChatHistoryLatest(networkID, target, limit) {
    return $Call.ByID(1762900095, networkID, target, limit);
}

/**
 * SaveNetwork saves network configuration without connecting
 * @param {$models.NetworkConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveNetwork(config) {
    return $Call.ByID(2045971702, config);
}

/**
 * SearchMessages performs full-text search across stored messages
 * @param {string} query
 * @param {number | null} networkID
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.SearchResult[]>}
 */
export function SearchMessages(query, networkID, limit) {
    return $Call.ByID(3203246577, query, networkID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * SendCommand sends a command from any channel or status window
 * Supports commands like /join #channel, /msg user message, or raw IRC commands
 * @param {number} networkID
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function SendCommand(networkID, command) {
    return $Call.ByID(2526227764, networkID, command);
}

/**
 * SendMessage sends a message to a channel or user
 * @param {number} networkID
 * @param {string} target
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(networkID, target, message) {
    return $Call.ByID(1496882310, networkID, target, message);
}

/**
 * SetChannelOpen sets the is_open state for a channel
 * @param {number} networkID
 * @param {string} channelName
 * @param {boolean} isOpen
 * @returns {$CancellablePromise<void>}
 */
export function SetChannelOpen(networkID, channelName, isOpen) {
    return $Call.ByID(1311700154, networkID, channelName, isOpen);
}

/**
 * SetLogConfig validates, applies, and persists a new file-logging
 * configuration. The new config is applied to the logger first so a bad path is
 * rejected before anything is written — on error the previous configuration and
 * stored settings are left untouched.
 * @param {boolean} enabled
 * @param {string} path
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetLogConfig(enabled, path, level) {
    return $Call.ByID(2238388953, enabled, path, level);
}

/**
 * SetPaneFocus sets focus on a pane and emits an event
 * @param {number} networkID
 * @param {string} paneType
 * @param {string} paneName
 * @returns {$CancellablePromise<void>}
 */
export function SetPaneFocus(networkID, paneType, paneName) {
    return $Call.ByID(3606120123, networkID, paneType, paneName);
}

/**
 * SetPluginConfig saves the configuration for a plugin
 * @param {string} pluginName
 * @param {{ [_ in string]?: any }} config
 * @returns {$CancellablePromise<void>}
 */
export function SetPluginConfig(pluginName, config) {
    return $Call.ByID(3525929918, pluginName, config);
}

/**
 * SetPrivateMessageOpen sets the is_open state for a private message conversation
 * @param {number} networkID
 * @param {string} targetUser
 * @param {boolean} isOpen
 * @returns {$CancellablePromise<void>}
 */
export function SetPrivateMessageOpen(networkID, targetUser, isOpen) {
    return $Call.ByID(1106422473, networkID, targetUser, isOpen);
}

/**
 * SetSetting persists a UI/app preference by key. After a successful write it
 * broadcasts a setting:changed event so every open window (e.g. the main window
 * and the standalone Settings window) can reconcile its in-memory copy live —
 * each webview is a separate JS context, so this is the only way a change in one
 * window reaches the others.
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSetting(key, value) {
    return $Call.ByID(4214292049, key, value);
}

/**
 * ToggleChannelAutoJoin toggles the auto-join setting for a channel
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<void>}
 */
export function ToggleChannelAutoJoin(networkID, channelName) {
    return $Call.ByID(1455136811, networkID, channelName);
}

/**
 * ToggleNetworkAutoConnect toggles the auto-connect setting for a network
 * @param {number} networkID
 * @returns {$CancellablePromise<void>}
 */
export function ToggleNetworkAutoConnect(networkID) {
    return $Call.ByID(945312860, networkID);
}

/**
 * UnpinMessage removes a pin
 * @param {number} messageID
 * @returns {$CancellablePromise<void>}
 */
export function UnpinMessage(messageID) {
    return $Call.ByID(2340933632, messageID);
}

// Private type creation functions
const $$createType0 = $models.BuildInfo.createFrom;
const $$createType1 = $models.ChannelListCacheResult.createFrom;
const $$createType2 = $models.ChannelInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = storage$0.Channel.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.CommandInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.LastOpenPane.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.LogConfig.createFrom;
const $$createType11 = storage$0.Message.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.MonitorEntry.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = irc$0.UserMeta.createFrom;
const $$createType17 = $Create.Map($Create.Any, $$createType16);
const $$createType18 = storage$0.Network.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $Create.Map($Create.Any, $Create.Any);
const $$createType21 = storage$0.PinnedMessage.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Map($Create.Any, $Create.Any);
const $$createType24 = storage$0.STSPolicy.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = $models.ServerCapabilitiesInfo.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = storage$0.Server.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $models.PluginInfo.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = storage$0.SearchResult.createFrom;
const $$createType33 = $Create.Array($$createType32);
