// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "./internal/events/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as irc$0 from "./internal/irc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./internal/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as unfurl$0 from "./internal/unfurl/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notifications$0 from "../../wailsapp/wails/v3/pkg/services/notifications/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddMonitor adds a nick to the network's durable buddy list and, if connected,
 * asks the server to track it (MONITOR +). It persists even when offline, so the
 * nick is (re-)sent on the next connect.
 * @param {number} networkID
 * @param {string} nick
 * @returns {$CancellablePromise<void>}
 */
export function AddMonitor(networkID, nick) {
    return $Call.ByID(3992658754, networkID, nick);
}

/**
 * AttachNotifications wires the Wails notification service into the app: it
 * installs the delivery backend, registers the categories, hooks the response
 * callback, captures the main window for focus, and seeds the prefs snapshot.
 * @param {notifications$0.NotificationService | null} svc
 * @param {application$0.WebviewWindow | null} win
 * @returns {$CancellablePromise<void>}
 */
export function AttachNotifications(svc, win) {
    return $Call.ByID(3749664784, svc, win);
}

/**
 * CheckForUpdates is the Wails-bound manual update trigger, called from the
 * "Check for Updates…" menu item and the About-pane button. On a dev build the
 * updater was never configured (see isReleaseVersion in main.go); rather than
 * silently doing nothing, we emit updater:unavailable so the frontend can toast
 * a friendly explanation. Otherwise CheckAndInstall opens the framework's themed
 * updater window, checks GitHub, and downloads/verifies/stages a newer release
 * if one exists. A manual check intentionally always shows the window (including
 * the reassuring "You're Up to Date" state).
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdates() {
    return $Call.ByID(2675659504);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearAllActivity() {
    return $Call.ByID(632029616);
}

/**
 * ClearPaneFocus clears focus from a pane and emits an event
 * @param {number} networkID
 * @param {string} paneType
 * @param {string} paneName
 * @returns {$CancellablePromise<void>}
 */
export function ClearPaneFocus(networkID, paneType, paneName) {
    return $Call.ByID(1854039756, networkID, paneType, paneName);
}

/**
 * ClearSTSPolicy removes the STS policy for a host. This is a deliberate security
 * downgrade (the next connection to that host may go plaintext again) exposed for
 * recovery/testing; the frontend gates it behind a confirmation. It broadcasts a
 * sts-policy event so any open window refreshes its badge.
 * @param {string} hostname
 * @returns {$CancellablePromise<void>}
 */
export function ClearSTSPolicy(hostname) {
    return $Call.ByID(2005130476, hostname);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearSeenActivity() {
    return $Call.ByID(784641832);
}

/**
 * CloseChannel hides a channel's buffer pane (is_open=false) WITHOUT leaving
 * the channel on the server. This is distinct from LeaveChannel, which sends a
 * real PART when you are joined. It emits EventChannelsChanged so every window's
 * server tree drops the pane; SetChannelOpen alone only emits a pane-blur event.
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<void>}
 */
export function CloseChannel(networkID, channelName) {
    return $Call.ByID(4004519506, networkID, channelName);
}

/**
 * ConnectNetwork connects to an IRC network (fresh connect, e.g. user-initiated
 * or startup auto-connect). Reconnect after an unexpected drop goes through
 * connectNetwork with reconnect=true so the client rejoins its whole session.
 * @param {$models.NetworkConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function ConnectNetwork(config) {
    return $Call.ByID(1245530049, config);
}

/**
 * ConnectSavedNetwork connects to a saved network by ID, building its config
 * from stored state. Used by the deep-link flow when a link targets a saved but
 * currently-disconnected network. No-op-safe to call; connectNetwork handles an
 * already-connected client.
 * @param {number} networkID
 * @returns {$CancellablePromise<void>}
 */
export function ConnectSavedNetwork(networkID) {
    return $Call.ByID(2804459446, networkID);
}

/**
 * DeleteNetwork deletes a network configuration
 * @param {number} networkID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNetwork(networkID) {
    return $Call.ByID(1276456224, networkID);
}

/**
 * DisablePlugin disables a plugin
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DisablePlugin(name) {
    return $Call.ByID(4075667952, name);
}

/**
 * DisableScript stops a script's timers and marks it disabled.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DisableScript(id) {
    return $Call.ByID(3841329420, id);
}

/**
 * DisconnectNetwork disconnects from a network
 * @param {number} networkID
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectNetwork(networkID) {
    return $Call.ByID(1238325307, networkID);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DismissActivity(id) {
    return $Call.ByID(2923849026, id);
}

/**
 * DismissInvite removes a single (sender, channel) invite.
 * @param {number} networkID
 * @param {string} inviter
 * @param {string} channel
 * @returns {$CancellablePromise<void>}
 */
export function DismissInvite(networkID, inviter, channel) {
    return $Call.ByID(4121992006, networkID, inviter, channel);
}

/**
 * DismissInvitesFrom removes all invites from a sender (without blocking them).
 * @param {number} networkID
 * @param {string} inviter
 * @returns {$CancellablePromise<void>}
 */
export function DismissInvitesFrom(networkID, inviter) {
    return $Call.ByID(1127010115, networkID, inviter);
}

/**
 * DrainPendingDeepLink marks the frontend ready (so later links emit live only)
 * and returns and clears any buffered cold-start deep link. Bound; called once
 * by the main window on startup.
 * @returns {$CancellablePromise<$models.PendingDeepLink | null>}
 */
export function DrainPendingDeepLink() {
    return $Call.ByID(1141503982).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * EnablePlugin enables a plugin
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function EnablePlugin(name) {
    return $Call.ByID(3947152785, name);
}

/**
 * EnableScript re-enables a previously disabled or runaway script.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function EnableScript(id) {
    return $Call.ByID(1252903669, id);
}

/**
 * FocusMainWindow raises the main window. Bound to the frontend and called from
 * the notification:navigate handler so window focus runs on the framework's
 * webview-request path rather than the off-main notification callback.
 * @returns {$CancellablePromise<void>}
 */
export function FocusMainWindow() {
    return $Call.ByID(1159429910);
}

/**
 * GetActivityItems returns the inbox rows, newest first.
 * @returns {$CancellablePromise<storage$0.ActivityItem[]>}
 */
export function GetActivityItems() {
    return $Call.ByID(2335822458).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetActivitySettings returns the stored settings, or defaults when unset.
 * @returns {$CancellablePromise<$models.ActivitySettings>}
 */
export function GetActivitySettings() {
    return $Call.ByID(3484511259).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetBuildInfo returns the version, commit, and build date stamped into the
 * binary at link time.
 * @returns {$CancellablePromise<$models.BuildInfo>}
 */
export function GetBuildInfo() {
    return $Call.ByID(3168473285).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetCachedChannelList returns the last-fetched LIST result for a network, if any.
 * It never triggers a fetch — callers use RequestChannelList to force a refresh.
 * @param {number} networkID
 * @returns {$CancellablePromise<$models.ChannelListCacheResult>}
 */
export function GetCachedChannelList(networkID) {
    return $Call.ByID(2256754220, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetChannelIDByName retrieves a channel ID by network ID and channel name
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<number | null>}
 */
export function GetChannelIDByName(networkID, channelName) {
    return $Call.ByID(1310009965, networkID, channelName);
}

/**
 * GetChannelInfo retrieves channel information including topic and users
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<$models.ChannelInfo | null>}
 */
export function GetChannelInfo(networkID, channelName) {
    return $Call.ByID(3499926414, networkID, channelName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetChannels retrieves channels for a network
 * @param {number} networkID
 * @returns {$CancellablePromise<storage$0.Channel[]>}
 */
export function GetChannels(networkID) {
    return $Call.ByID(1369558439, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetCommands returns metadata for every known command (built-ins merged with
 * plugin commands). Bound to the frontend via Wails.
 * @returns {$CancellablePromise<$models.CommandInfo[]>}
 */
export function GetCommands() {
    return $Call.ByID(983453965).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetConnectionStatus returns whether a network is connected
 * @param {number} networkID
 * @returns {$CancellablePromise<boolean>}
 */
export function GetConnectionStatus(networkID) {
    return $Call.ByID(1041368369, networkID);
}

/**
 * GetCurrentNick returns the nick the server currently knows us by on a network,
 * which can differ from the configured nick while a nick collision is being
 * resolved. Returns an empty string when the network has no active client.
 * @param {number} networkID
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentNick(networkID) {
    return $Call.ByID(869658591, networkID);
}

/**
 * GetDefaultLogPath returns the default log file location, for use as a UI
 * placeholder when the user hasn't chosen a custom path.
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultLogPath() {
    return $Call.ByID(3647489945);
}

/**
 * GetInvites returns the network's non-expired pending invites, newest-first.
 * @param {number} networkID
 * @returns {$CancellablePromise<$models.InviteView[]>}
 */
export function GetInvites(networkID) {
    return $Call.ByID(1064767131, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetJoinedChannels retrieves channels where the current user is still a member
 * @param {number} networkID
 * @returns {$CancellablePromise<storage$0.Channel[]>}
 */
export function GetJoinedChannels(networkID) {
    return $Call.ByID(209386014, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetLastOpenPane retrieves the most recently updated open channel or PM conversation
 * @returns {$CancellablePromise<$models.LastOpenPane | null>}
 */
export function GetLastOpenPane() {
    return $Call.ByID(1367469045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetLogConfig returns the current file-logging configuration, with defaults
 * applied for any unset values.
 * @returns {$CancellablePromise<$models.LogConfig>}
 */
export function GetLogConfig() {
    return $Call.ByID(3565499149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetMessageByMsgID resolves a message by its IRCv3 msgid so the frontend can
 * render a +draft/reply parent preview and jump to it (possibly cross-buffer).
 * @param {number} networkID
 * @param {string} msgid
 * @returns {$CancellablePromise<storage$0.Message>}
 */
export function GetMessageByMsgID(networkID, msgid) {
    return $Call.ByID(1122817005, networkID, msgid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetMessageIDByMsgID resolves an IRCv3 msgid to its numeric message id (0 if not found).
 * @param {number} networkID
 * @param {string} msgid
 * @returns {$CancellablePromise<number>}
 */
export function GetMessageIDByMsgID(networkID, msgid) {
    return $Call.ByID(3202657846, networkID, msgid);
}

/**
 * GetMessages retrieves messages for a network and channel
 * @param {number} networkID
 * @param {number | null} channelID
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessages(networkID, channelID, limit) {
    return $Call.ByID(3832618599, networkID, channelID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetMessagesAfter retrieves up to `limit` messages newer than afterID (exclusive),
 * chronological order. Used to scroll forward out of an anchored context window.
 * @param {number} networkID
 * @param {number | null} channelID
 * @param {number} afterID
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessagesAfter(networkID, channelID, afterID, limit) {
    return $Call.ByID(4016273103, networkID, channelID, afterID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetMessagesAround retrieves a window of messages around a target message id,
 * so the frontend can "jump" to a pinned message with surrounding context.
 * @param {number} networkID
 * @param {number | null} channelID
 * @param {number} targetID
 * @param {number} window
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessagesAround(networkID, channelID, targetID, window) {
    return $Call.ByID(468669170, networkID, channelID, targetID, window).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetMessagesBefore retrieves up to `limit` messages older than beforeID (exclusive),
 * chronological order. Used for scrollback pagination. channelID nil = status pane.
 * @param {number} networkID
 * @param {number | null} channelID
 * @param {number} beforeID
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessagesBefore(networkID, channelID, beforeID, limit) {
    return $Call.ByID(2291548608, networkID, channelID, beforeID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetMessagesBeforeTime retrieves up to `limit` messages older than `beforeISO`
 * (an ISO8601/RFC3339 timestamp) by server-time, chronological order. Unlike
 * GetMessagesBefore (id-keyed), this surfaces CHATHISTORY-backfilled rows (high
 * id, old timestamp). A non-empty pmTarget selects a PM conversation; otherwise
 * channelID selects a channel (nil = status pane). Used for unified local + server
 * scrollback pagination.
 * 
 * The cursor is a string (not time.Time) deliberately: a time.Time parameter in a
 * Wails-bound method makes the binding generator emit a time.Time class for every
 * timestamp field, which breaks `new Date(msg.timestamp)` across the frontend.
 * @param {number} networkID
 * @param {number | null} channelID
 * @param {string} pmTarget
 * @param {string} beforeISO
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetMessagesBeforeTime(networkID, channelID, pmTarget, beforeISO, limit) {
    return $Call.ByID(1921588377, networkID, channelID, pmTarget, beforeISO, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetMonitorList returns the network's durable MONITOR buddy list joined with each
 * nick's current online state (unknown until the first 730/731, defaulting offline).
 * @param {number} networkID
 * @returns {$CancellablePromise<$models.MonitorEntry[]>}
 */
export function GetMonitorList(networkID) {
    return $Call.ByID(3280037895, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * GetMonitorPresence returns the live online state of every nick currently tracked
 * via MONITOR (lowercased nick -> online), including auto-monitored PM
 * correspondents that are not durable buddies. The frontend uses it to seed the
 * DM-list presence dots, covering 730/731 replies that arrived before the UI
 * subscribed to the live 'monitor-event'.
 * @param {number} networkID
 * @returns {$CancellablePromise<{ [_ in string]?: boolean }>}
 */
export function GetMonitorPresence(networkID) {
    return $Call.ByID(2494040686, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetNetworkBots returns the lowercased nicks recognized as IRCv3 bots for a
 * network this session. The frontend calls this to hydrate its bot set when a
 * window opens or reloads; live additions arrive via the "bot-event" event.
 * Returns an empty slice when the network is not currently connected.
 * @param {number} networkID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetNetworkBots(networkID) {
    return $Call.ByID(1037950925, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetNetworkUserMeta returns the live roster attributes (away/account/host) for
 * a network this session, keyed by lowercased nick. The frontend calls this to
 * hydrate its roster metadata when a window opens or reloads; live changes
 * arrive via the "usermeta-event" event. Returns an empty map when the network
 * is not currently connected.
 * @param {number} networkID
 * @returns {$CancellablePromise<{ [_ in string]?: irc$0.UserMeta }>}
 */
export function GetNetworkUserMeta(networkID) {
    return $Call.ByID(1426666641, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * GetNetworks retrieves all networks. Secret values are stripped before the
 * networks reach the frontend; Has* flags report presence instead.
 * @returns {$CancellablePromise<storage$0.Network[]>}
 */
export function GetNetworks() {
    return $Call.ByID(366685148).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetNicknameColor gets color for a single nickname
 * @param {number} networkID
 * @param {string} nickname
 * @returns {$CancellablePromise<string>}
 */
export function GetNicknameColor(networkID, nickname) {
    return $Call.ByID(2930834622, networkID, nickname);
}

/**
 * GetNicknameColorsBatch gets colors for multiple nicknames efficiently
 * @param {number} networkID
 * @param {string[]} nicknames
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetNicknameColorsBatch(networkID, nicknames) {
    return $Call.ByID(4229567593, networkID, nicknames).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * GetOpenChannels returns the channels the sidebar should show for a network:
 * exactly those whose buffer is open (is_open=1). is_open is the single source of
 * truth for buffer visibility — a self-JOIN opens it, and PART/KICK/join-error and
 * CloseChannel close it — so Close/Leave actually drop the pane even while you are
 * still a member. (Roster-based visibility is deliberately NOT used here: it would
 * keep a joined-but-closed channel pinned to the sidebar, which is the bug where
 * "Close Channel" appeared to do nothing. The roster-inclusive storage.GetOpenChannels
 * still backs the reconnect rejoin path in client.channelsToJoin.)
 * @param {number} networkID
 * @returns {$CancellablePromise<storage$0.Channel[]>}
 */
export function GetOpenChannels(networkID) {
    return $Call.ByID(564233579, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetPendingNetworkPrefill returns the pending Add Network prefill (if any) and
 * clears it, so it is consumed exactly once. Bound for the settings window.
 * @returns {$CancellablePromise<$models.NetworkPrefill | null>}
 */
export function GetPendingNetworkPrefill() {
    return $Call.ByID(2272832728).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetPinnedMessages retrieves pinned messages for a network and channel
 * @param {number} networkID
 * @param {number | null} channelID
 * @returns {$CancellablePromise<storage$0.PinnedMessage[]>}
 */
export function GetPinnedMessages(networkID, channelID) {
    return $Call.ByID(380870585, networkID, channelID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GetPluginConfig gets the configuration for a plugin
 * @param {string} pluginName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetPluginConfig(pluginName) {
    return $Call.ByID(1436487730, pluginName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * GetPluginConfigSchema gets the configuration schema for a plugin
 * @param {string} pluginName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetPluginConfigSchema(pluginName) {
    return $Call.ByID(249168125, pluginName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * GetPrivateMessageConversations retrieves a list of users with private message conversations
 * @param {number} networkID
 * @param {boolean} openOnly
 * @returns {$CancellablePromise<string[]>}
 */
export function GetPrivateMessageConversations(networkID, openOnly) {
    return $Call.ByID(839521643, networkID, openOnly).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetPrivateMessages retrieves private messages for a network and user
 * @param {number} networkID
 * @param {string} targetUser
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.Message[]>}
 */
export function GetPrivateMessages(networkID, targetUser, limit) {
    return $Call.ByID(2750786118, networkID, targetUser, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetSTSPolicies returns every stored IRCv3 STS policy (host → enforced TLS port +
 * expiry), for the settings panel to render an "enforced until" badge per server.
 * @returns {$CancellablePromise<storage$0.STSPolicy[]>}
 */
export function GetSTSPolicies() {
    return $Call.ByID(3662233731).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * GetServerCapabilities retrieves server capabilities from ISUPPORT for a network
 * @param {number} networkID
 * @returns {$CancellablePromise<$models.ServerCapabilitiesInfo | null>}
 */
export function GetServerCapabilities(networkID) {
    return $Call.ByID(1639110850, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * GetServers retrieves server addresses for a network
 * @param {number} networkID
 * @returns {$CancellablePromise<storage$0.Server[]>}
 */
export function GetServers(networkID) {
    return $Call.ByID(4270553301, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * GetSetting returns a persisted UI/app preference by key. A missing key
 * returns an empty string (not an error) so the frontend can apply its default.
 * Used for preferences like theme mode and accent that can't live in the
 * WKWebView's localStorage because macOS drops it between launches.
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetSetting(key) {
    return $Call.ByID(48053349, key);
}

/**
 * Greet returns a greeting for the given name (kept for compatibility)
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(2659711170, name);
}

/**
 * IgnoreInviteSender blocks a sender's invites for the session and removes any
 * already pending. Session-only and invite-scoped (not a global /ignore).
 * @param {number} networkID
 * @param {string} inviter
 * @returns {$CancellablePromise<void>}
 */
export function IgnoreInviteSender(networkID, inviter) {
    return $Call.ByID(181327979, networkID, inviter);
}

/**
 * LeaveChannel leaves an IRC channel by sending a PART when joined and
 * connected. It is overloaded: on the not-joined / no-client / lookup-error
 * paths it instead just hides the buffer pane (SetChannelOpen false) and emits
 * EventChannelsChanged. The UI only offers "Leave Channel" when joined (see
 * server-tree.tsx), so in practice this always takes the PART path; callers
 * that want a pure buffer-hide should use CloseChannel instead.
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<void>}
 */
export function LeaveChannel(networkID, channelName) {
    return $Call.ByID(2303728547, networkID, channelName);
}

/**
 * ListPlugins returns information about all plugins
 * @returns {$CancellablePromise<$models.PluginInfo[]>}
 */
export function ListPlugins() {
    return $Call.ByID(3314730135).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * ListScripts returns a snapshot of every loaded script and its current status.
 * @returns {$CancellablePromise<$models.ScriptInfo[]>}
 */
export function ListScripts() {
    return $Call.ByID(3467580111).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function MarkActivitySeen(id) {
    return $Call.ByID(820950458, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MarkAllActivitySeen() {
    return $Call.ByID(709302001);
}

/**
 * NewScript creates a new script directory with a starter file under the
 * scripts directory and returns the path to the created file.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function NewScript(name) {
    return $Call.ByID(3860963958, name);
}

/**
 * OnEvent implements the events.Subscriber interface to forward events to frontend
 * @param {events$0.Event} event
 * @returns {$CancellablePromise<void>}
 */
export function OnEvent(event) {
    return $Call.ByID(844865600, event);
}

/**
 * OpenScriptsDir reveals the scripts directory in the OS file manager.
 * Uses "open" on macOS, "xdg-open" on Linux, and "explorer" on Windows.
 * Note: no existing reveal-in-finder helper was found in the codebase;
 * this is a minimal exec-based implementation.
 * @returns {$CancellablePromise<void>}
 */
export function OpenScriptsDir() {
    return $Call.ByID(1353712790);
}

/**
 * OpenSettings opens (or focuses) the standalone Settings window.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(2024983644);
}

/**
 * OpenSettingsAbout opens the Settings window to the about section.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettingsAbout() {
    return $Call.ByID(2440832785);
}

/**
 * OpenSettingsDisplay opens the Settings window to the display section.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettingsDisplay() {
    return $Call.ByID(2211152578);
}

/**
 * OpenSettingsNetworks opens the Settings window to the networks section.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettingsNetworks() {
    return $Call.ByID(1081996467);
}

/**
 * OpenSettingsPlugins opens the Settings window to the plugins section.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettingsPlugins() {
    return $Call.ByID(2435594228);
}

/**
 * PinMessage pins a message in a network/channel (channelID nil for status/PM panes)
 * @param {number} networkID
 * @param {number} messageID
 * @param {number | null} channelID
 * @returns {$CancellablePromise<void>}
 */
export function PinMessage(networkID, messageID, channelID) {
    return $Call.ByID(1631361803, networkID, messageID, channelID);
}

/**
 * PrintLocalLines writes client-local system lines (e.g. /help output) into a
 * buffer through the normal message pipeline so they render and scroll like
 * other system notices. target: "" or "status" => status buffer; "#name" =>
 * channel; otherwise a PM peer nick.
 * @param {number} networkID
 * @param {string} target
 * @param {string[]} lines
 * @returns {$CancellablePromise<void>}
 */
export function PrintLocalLines(networkID, target, lines) {
    return $Call.ByID(821357734, networkID, target, lines);
}

/**
 * ReloadPlugin reloads a plugin
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ReloadPlugin(name) {
    return $Call.ByID(2644883255, name);
}

/**
 * ReloadScript reloads a script from disk by its ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ReloadScript(id) {
    return $Call.ByID(3845221199, id);
}

/**
 * RemoveMonitor removes a nick from the buddy list and stops tracking it — unless
 * the nick still has an open PM, in which case presence tracking continues for
 * the DM-list dot (the union rule).
 * @param {number} networkID
 * @param {string} nick
 * @returns {$CancellablePromise<void>}
 */
export function RemoveMonitor(networkID, nick) {
    return $Call.ByID(2238775289, networkID, nick);
}

/**
 * RequestChannelBans asks the server for a channel's ban list. The result is delivered
 * asynchronously to the frontend via the "channel.banlist" event.
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<void>}
 */
export function RequestChannelBans(networkID, channelName) {
    return $Call.ByID(2034965975, networkID, channelName);
}

/**
 * RequestChannelList sends the LIST command to request available channels from the server
 * @param {number} networkID
 * @returns {$CancellablePromise<void>}
 */
export function RequestChannelList(networkID) {
    return $Call.ByID(2678000793, networkID);
}

/**
 * RequestChatHistoryBefore asks the server to replay up to `limit` messages older
 * than beforeISO (an ISO8601 timestamp) for target. Used by scroll-to-top deep
 * backscroll once the local store is exhausted.
 * @param {number} networkID
 * @param {string} target
 * @param {string} beforeISO
 * @param {number} limit
 * @returns {$CancellablePromise<void>}
 */
export function RequestChatHistoryBefore(networkID, target, beforeISO, limit) {
    return $Call.ByID(3507479247, networkID, target, beforeISO, limit);
}

/**
 * RequestChatHistoryLatest asks the server to replay the most recent `limit`
 * messages for target (channel name or PM nick). Used for on-open catch-up of a
 * PM/query pane (channel catch-up fires automatically on JOIN). Replays are stored
 * and deduped by msgid; the frontend learns of them via the "history-event".
 * @param {number} networkID
 * @param {string} target
 * @param {number} limit
 * @returns {$CancellablePromise<void>}
 */
export function RequestChatHistoryLatest(networkID, target, limit) {
    return $Call.ByID(1762900095, networkID, target, limit);
}

/**
 * RequestNotificationPermission asks the OS for notification permission. Bound to
 * the frontend; called when the user enables notifications in settings.
 * @returns {$CancellablePromise<boolean>}
 */
export function RequestNotificationPermission() {
    return $Call.ByID(3109134518);
}

/**
 * SaveNetwork saves network configuration without connecting
 * @param {$models.NetworkConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveNetwork(config) {
    return $Call.ByID(2045971702, config);
}

/**
 * SearchMessages performs full-text search across stored messages
 * @param {string} query
 * @param {number | null} networkID
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.SearchResult[]>}
 */
export function SearchMessages(query, networkID, limit) {
    return $Call.ByID(3203246577, query, networkID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * SendCommand sends a command from any channel or status window
 * Supports commands like /join #channel, /msg user message, or raw IRC commands
 * @param {number} networkID
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function SendCommand(networkID, command) {
    return $Call.ByID(2526227764, networkID, command);
}

/**
 * SendMessage sends a message to a channel or user
 * @param {number} networkID
 * @param {string} target
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(networkID, target, message) {
    return $Call.ByID(1496882310, networkID, target, message);
}

/**
 * SendMessageWithContext sends a PRIVMSG carrying optional IRCv3 client tags:
 * replyMsgID -> +draft/reply, channelContext -> +draft/channel-context. Empty
 * strings omit the corresponding tag.
 * @param {number} networkID
 * @param {string} target
 * @param {string} message
 * @param {string} replyMsgID
 * @param {string} channelContext
 * @returns {$CancellablePromise<void>}
 */
export function SendMessageWithContext(networkID, target, message, replyMsgID, channelContext) {
    return $Call.ByID(242389933, networkID, target, message, replyMsgID, channelContext);
}

/**
 * SendTyping emits an IRCv3 +typing client tag (active/paused/done) for target.
 * Best-effort: a disconnected network or a server without message-tags yields no
 * error so the frontend's typing state machine can fire freely.
 * @param {number} networkID
 * @param {string} target
 * @param {string} state
 * @returns {$CancellablePromise<void>}
 */
export function SendTyping(networkID, target, state) {
    return $Call.ByID(892939144, networkID, target, state);
}

/**
 * SetActivitySettings persists the settings as JSON.
 * @param {$models.ActivitySettings} s
 * @returns {$CancellablePromise<void>}
 */
export function SetActivitySettings(s) {
    return $Call.ByID(233151559, s);
}

/**
 * SetChannelOpen sets the is_open state for a channel
 * @param {number} networkID
 * @param {string} channelName
 * @param {boolean} isOpen
 * @returns {$CancellablePromise<void>}
 */
export function SetChannelOpen(networkID, channelName, isOpen) {
    return $Call.ByID(1311700154, networkID, channelName, isOpen);
}

/**
 * SetLogConfig validates, applies, and persists a new file-logging
 * configuration. The new config is applied to the logger first so a bad path is
 * rejected before anything is written — on error the previous configuration and
 * stored settings are left untouched.
 * @param {boolean} enabled
 * @param {string} path
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetLogConfig(enabled, path, level) {
    return $Call.ByID(2238388953, enabled, path, level);
}

/**
 * SetPaneFocus sets focus on a pane and emits an event
 * @param {number} networkID
 * @param {string} paneType
 * @param {string} paneName
 * @returns {$CancellablePromise<void>}
 */
export function SetPaneFocus(networkID, paneType, paneName) {
    return $Call.ByID(3606120123, networkID, paneType, paneName);
}

/**
 * SetPluginConfig saves the configuration for a plugin
 * @param {string} pluginName
 * @param {{ [_ in string]?: any }} config
 * @returns {$CancellablePromise<void>}
 */
export function SetPluginConfig(pluginName, config) {
    return $Call.ByID(3525929918, pluginName, config);
}

/**
 * SetPrivateMessageOpen sets the is_open state for a private message conversation
 * @param {number} networkID
 * @param {string} targetUser
 * @param {boolean} isOpen
 * @returns {$CancellablePromise<void>}
 */
export function SetPrivateMessageOpen(networkID, targetUser, isOpen) {
    return $Call.ByID(1106422473, networkID, targetUser, isOpen);
}

/**
 * SetSetting persists a UI/app preference by key. After a successful write it
 * broadcasts a setting:changed event so every open window (e.g. the main window
 * and the standalone Settings window) can reconcile its in-memory copy live —
 * each webview is a separate JS context, so this is the only way a change in one
 * window reaches the others.
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSetting(key, value) {
    return $Call.ByID(4214292049, key, value);
}

/**
 * SkipUpdateVersion is the Wails-bound handler for the in-app update prompt's
 * "Skip This Version" button. It persists the version to the settings table so
 * the background check stops re-surfacing it — including across restarts, which
 * the framework updater's own in-memory skip does not survive. A newer release
 * still prompts (see shouldSurfaceUpdate), and a manual "Check for Updates…"
 * still shows the skipped version, since that is an explicit user request.
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function SkipUpdateVersion(version) {
    return $Call.ByID(3143090493, version);
}

/**
 * ToggleChannelAutoJoin toggles the auto-join setting for a channel
 * @param {number} networkID
 * @param {string} channelName
 * @returns {$CancellablePromise<void>}
 */
export function ToggleChannelAutoJoin(networkID, channelName) {
    return $Call.ByID(1455136811, networkID, channelName);
}

/**
 * ToggleNetworkAutoConnect toggles the auto-connect setting for a network
 * @param {number} networkID
 * @returns {$CancellablePromise<void>}
 */
export function ToggleNetworkAutoConnect(networkID) {
    return $Call.ByID(945312860, networkID);
}

/**
 * UnfurlURL returns a preview card for rawURL. It is the single network egress
 * point for the feature: the webview never fetches preview content itself. A
 * cache hit performs no network I/O. Failures are reported via Status
 * ("blocked" for SSRF/scheme rejections, "error" otherwise) rather than a Go
 * error, so the frontend can render a quiet inline state; a Go error is returned
 * only for unexpected internal (cache) failures.
 * @param {string} rawURL
 * @returns {$CancellablePromise<unfurl$0.LinkPreview | null>}
 */
export function UnfurlURL(rawURL) {
    return $Call.ByID(2006376526, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType47($result);
    }));
}

/**
 * UnpinMessage removes a pin
 * @param {number} messageID
 * @returns {$CancellablePromise<void>}
 */
export function UnpinMessage(messageID) {
    return $Call.ByID(2340933632, messageID);
}

// Private type creation functions
const $$createType0 = $models.PendingDeepLink.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = storage$0.ActivityItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ActivitySettings.createFrom;
const $$createType5 = $models.BuildInfo.createFrom;
const $$createType6 = $models.ChannelListCacheResult.createFrom;
const $$createType7 = $models.ChannelInfo.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = storage$0.Channel.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.CommandInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.InviteView.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.LastOpenPane.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $models.LogConfig.createFrom;
const $$createType18 = storage$0.Message.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.MonitorEntry.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $Create.Map($Create.Any, $Create.Any);
const $$createType23 = $Create.Array($Create.Any);
const $$createType24 = irc$0.UserMeta.createFrom;
const $$createType25 = $Create.Map($Create.Any, $$createType24);
const $$createType26 = storage$0.Network.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = $Create.Map($Create.Any, $Create.Any);
const $$createType29 = $models.NetworkPrefill.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = storage$0.PinnedMessage.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $Create.Map($Create.Any, $Create.Any);
const $$createType34 = storage$0.STSPolicy.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = $models.ServerCapabilitiesInfo.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = storage$0.Server.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = $models.PluginInfo.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = $models.ScriptInfo.createFrom;
const $$createType43 = $Create.Array($$createType42);
const $$createType44 = storage$0.SearchResult.createFrom;
const $$createType45 = $Create.Array($$createType44);
const $$createType46 = unfurl$0.LinkPreview.createFrom;
const $$createType47 = $Create.Nullable($$createType46);
