// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./internal/storage/models.js";

/**
 * BuildInfo is the build metadata exposed to the frontend. buildDate is a
 * string (ISO-8601), never time.Time: a time.Time in a Wails-bound signature
 * breaks the generated TypeScript model.
 */
export class BuildInfo {
    /**
     * Creates a new BuildInfo instance.
     * @param {Partial<BuildInfo>} [$$source = {}] - The source object to create the BuildInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("commit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commit"] = "";
        }
        if (!("buildDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BuildInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuildInfo(/** @type {Partial<BuildInfo>} */($$parsedSource));
    }
}

/**
 * ChannelInfo represents channel information with users
 */
export class ChannelInfo {
    /**
     * Creates a new ChannelInfo instance.
     * @param {Partial<ChannelInfo>} [$$source = {}] - The source object to create the ChannelInfo.
     */
    constructor($$source = {}) {
        if (!("channel" in $$source)) {
            /**
             * @member
             * @type {storage$0.Channel | null}
             */
            this["channel"] = null;
        }
        if (!("users" in $$source)) {
            /**
             * @member
             * @type {storage$0.ChannelUser[]}
             */
            this["users"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ServerCapabilitiesInfo | null | undefined}
             */
            this["capabilities"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChannelInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channel" in $$parsedSource) {
            $$parsedSource["channel"] = $$createField0_0($$parsedSource["channel"]);
        }
        if ("users" in $$parsedSource) {
            $$parsedSource["users"] = $$createField1_0($$parsedSource["users"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField2_0($$parsedSource["capabilities"]);
        }
        return new ChannelInfo(/** @type {Partial<ChannelInfo>} */($$parsedSource));
    }
}

/**
 * ChannelListCacheResult is the cached LIST result returned to the frontend.
 * FetchedAt is unix milliseconds; Found is false when no cache exists for the network.
 */
export class ChannelListCacheResult {
    /**
     * Creates a new ChannelListCacheResult instance.
     * @param {Partial<ChannelListCacheResult>} [$$source = {}] - The source object to create the ChannelListCacheResult.
     */
    constructor($$source = {}) {
        if (!("channels" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["channels"] = [];
        }
        if (!("fetchedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fetchedAt"] = 0;
        }
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["found"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelListCacheResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChannelListCacheResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField0_0($$parsedSource["channels"]);
        }
        return new ChannelListCacheResult(/** @type {Partial<ChannelListCacheResult>} */($$parsedSource));
    }
}

/**
 * LastOpenPane represents the last open pane (channel or PM conversation)
 */
export class LastOpenPane {
    /**
     * Creates a new LastOpenPane instance.
     * @param {Partial<LastOpenPane>} [$$source = {}] - The source object to create the LastOpenPane.
     */
    constructor($$source = {}) {
        if (!("network_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["network_id"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * "channel" or "pm"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * Channel name or PM target user
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LastOpenPane instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LastOpenPane}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LastOpenPane(/** @type {Partial<LastOpenPane>} */($$parsedSource));
    }
}

/**
 * LogConfig is the file-logging configuration exposed to the frontend.
 */
export class LogConfig {
    /**
     * Creates a new LogConfig instance.
     * @param {Partial<LogConfig>} [$$source = {}] - The source object to create the LogConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * "debug" | "info" | "warn" | "error"
             * @member
             * @type {string}
             */
            this["level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogConfig(/** @type {Partial<LogConfig>} */($$parsedSource));
    }
}

/**
 * NetworkConfig represents network configuration
 */
export class NetworkConfig {
    /**
     * Creates a new NetworkConfig instance.
     * @param {Partial<NetworkConfig>} [$$source = {}] - The source object to create the NetworkConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * Deprecated: use Servers
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * Deprecated: use Servers
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("tls" in $$source)) {
            /**
             * Deprecated: use Servers
             * @member
             * @type {boolean}
             */
            this["tls"] = false;
        }
        if (!("servers" in $$source)) {
            /**
             * New: multiple server addresses
             * @member
             * @type {ServerConfig[]}
             */
            this["servers"] = [];
        }
        if (!("nickname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nickname"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("realname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["realname"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("sasl_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sasl_enabled"] = false;
        }
        if (!("sasl_mechanism" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sasl_mechanism"] = "";
        }
        if (!("sasl_username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sasl_username"] = "";
        }
        if (!("sasl_password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sasl_password"] = "";
        }
        if (!("sasl_external_cert" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sasl_external_cert"] = "";
        }
        if (!("auto_connect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_connect"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField4_0($$parsedSource["servers"]);
        }
        return new NetworkConfig(/** @type {Partial<NetworkConfig>} */($$parsedSource));
    }
}

/**
 * PluginInfo represents plugin information for the frontend
 */
export class PluginInfo {
    /**
     * Creates a new PluginInfo instance.
     * @param {Partial<PluginInfo>} [$$source = {}] - The source object to create the PluginInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["author"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["events"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["permissions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["metadata_types"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["config_schema"] = undefined;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInfo}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType10;
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType10;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField4_0($$parsedSource["events"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField5_0($$parsedSource["permissions"]);
        }
        if ("metadata_types" in $$parsedSource) {
            $$parsedSource["metadata_types"] = $$createField6_0($$parsedSource["metadata_types"]);
        }
        if ("config_schema" in $$parsedSource) {
            $$parsedSource["config_schema"] = $$createField7_0($$parsedSource["config_schema"]);
        }
        return new PluginInfo(/** @type {Partial<PluginInfo>} */($$parsedSource));
    }
}

/**
 * ServerCapabilitiesInfo represents server capabilities for frontend
 */
export class ServerCapabilitiesInfo {
    /**
     * Creates a new ServerCapabilitiesInfo instance.
     * @param {Partial<ServerCapabilitiesInfo>} [$$source = {}] - The source object to create the ServerCapabilitiesInfo.
     */
    constructor($$source = {}) {
        if (!("prefix" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["prefix"] = {};
        }
        if (!("prefix_string" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prefix_string"] = "";
        }
        if (!("chanmodes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chanmodes"] = "";
        }
        if (!("chanmodes_a" in $$source)) {
            /**
             * Resolved CHANMODES classes (sorted letters), with RFC1459 defaults applied.
             * A=list (bans), B=always-param (key), C=param-on-set (limit), D=boolean flag.
             * @member
             * @type {string}
             */
            this["chanmodes_a"] = "";
        }
        if (!("chanmodes_b" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chanmodes_b"] = "";
        }
        if (!("chanmodes_c" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chanmodes_c"] = "";
        }
        if (!("chanmodes_d" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chanmodes_d"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerCapabilitiesInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerCapabilitiesInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prefix" in $$parsedSource) {
            $$parsedSource["prefix"] = $$createField0_0($$parsedSource["prefix"]);
        }
        return new ServerCapabilitiesInfo(/** @type {Partial<ServerCapabilitiesInfo>} */($$parsedSource));
    }
}

/**
 * ServerConfig represents a single server address configuration
 */
export class ServerConfig {
    /**
     * Creates a new ServerConfig instance.
     * @param {Partial<ServerConfig>} [$$source = {}] - The source object to create the ServerConfig.
     */
    constructor($$source = {}) {
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("tls" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tls"] = false;
        }
        if (!("order" in $$source)) {
            /**
             * Order for fallback (lower = higher priority)
             * @member
             * @type {number}
             */
            this["order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig(/** @type {Partial<ServerConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = storage$0.Channel.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = storage$0.ChannelUser.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ServerCapabilitiesInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ServerConfig.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
