// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UserMeta holds the live, session-local roster attributes Cascade tracks for a
 * nick via the IRCv3 caps away-notify, account-notify, extended-join, chghost,
 * and account-tag. It is deliberately not persisted: a nick's away/account/host
 * is only meaningful for the current session and is rebuilt on reconnect.
 */
export class UserMeta {
    /**
     * Creates a new UserMeta instance.
     * @param {Partial<UserMeta>} [$$source = {}] - The source object to create the UserMeta.
     */
    constructor($$source = {}) {
        if (!("away" in $$source)) {
            /**
             * true while the user is marked away (away-notify)
             * @member
             * @type {boolean}
             */
            this["away"] = false;
        }
        if (!("away_message" in $$source)) {
            /**
             * the away reason, if any
             * @member
             * @type {string}
             */
            this["away_message"] = "";
        }
        if (!("account" in $$source)) {
            /**
             * account the user is logged in as; "" when not logged in
             * @member
             * @type {string}
             */
            this["account"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * user@host learned from chghost; "" until seen
             * @member
             * @type {string}
             */
            this["host"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserMeta(/** @type {Partial<UserMeta>} */($$parsedSource));
    }
}
