// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LinkPreview holds the extracted preview data for a URL. Status is left empty
 * here; the App layer stamps "ok"/"blocked"/"error" when persisting.
 */
export class LinkPreview {
    /**
     * Creates a new LinkPreview instance.
     * @param {Partial<LinkPreview>} [$$source = {}] - The source object to create the LinkPreview.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("siteName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["siteName"] = "";
        }
        if (!("imageDataUri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageDataUri"] = "";
        }
        if (!("fetchedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fetchedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LinkPreview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinkPreview(/** @type {Partial<LinkPreview>} */($$parsedSource));
    }
}
