package irc

import (
	"sync"

	"github.com/matt0x6f/irc-client/internal/logger"
)

// automaticRequest is a protocol follow-up generated by an inbound event. These
// requests must not be written directly from callbacks: a callback backlog can
// otherwise turn individually harmless NAMES/WHO/CHATHISTORY requests into one
// large wire burst when the backlog catches up.
type automaticRequest struct {
	name string
	run  func() error
}

// outboundRequestDispatcher serializes and rate-limits protocol requests that
// Cascade generates automatically. It is separate from callbackDispatcher so a
// slow server-request budget never delays storage, plugins, or the frontend.
type outboundRequestDispatcher struct {
	mu       sync.Mutex
	ready    *sync.Cond
	queue    []automaticRequest
	stopping bool
	wait     func()
	done     chan struct{}
}

func newOutboundRequestDispatcher(wait func()) *outboundRequestDispatcher {
	d := &outboundRequestDispatcher{wait: wait, done: make(chan struct{})}
	d.ready = sync.NewCond(&d.mu)
	go d.run()
	return d
}

// enqueue returns immediately; the request is paced by the worker. It returns
// false once connection teardown has begun.
func (d *outboundRequestDispatcher) enqueue(name string, run func() error) bool {
	if d == nil || run == nil {
		return false
	}
	d.mu.Lock()
	defer d.mu.Unlock()
	if d.stopping {
		return false
	}
	d.queue = append(d.queue, automaticRequest{name: name, run: run})
	d.ready.Signal()
	return true
}

// stopNow drops unsent work. Automatic enrichment belongs to this connection
// only and must never leak onto a dead or replacement socket.
func (d *outboundRequestDispatcher) stopNow() {
	if d == nil {
		return
	}
	d.mu.Lock()
	d.stopping = true
	for i := range d.queue {
		d.queue[i] = automaticRequest{}
	}
	d.queue = nil
	d.ready.Broadcast()
	d.mu.Unlock()
}

func (d *outboundRequestDispatcher) run() {
	defer close(d.done)
	for {
		d.mu.Lock()
		for len(d.queue) == 0 && !d.stopping {
			d.ready.Wait()
		}
		if d.stopping {
			d.mu.Unlock()
			return
		}
		request := d.queue[0]
		d.queue[0] = automaticRequest{}
		d.queue = d.queue[1:]
		if len(d.queue) == 0 {
			d.queue = nil
		}
		d.mu.Unlock()

		if d.wait != nil {
			d.wait()
		}

		// Teardown may have happened while waiting for the shared rate limiter.
		d.mu.Lock()
		stopping := d.stopping
		d.mu.Unlock()
		if stopping {
			return
		}
		if err := request.run(); err != nil {
			logger.Log.Debug().Err(err).Str("request", request.name).Msg("Automatic IRC request failed")
		}
	}
}
