// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectNetwork(arg1) {
  return window['go']['main']['App']['ConnectNetwork'](arg1);
}

export function DeleteNetwork(arg1) {
  return window['go']['main']['App']['DeleteNetwork'](arg1);
}

export function DisablePlugin(arg1) {
  return window['go']['main']['App']['DisablePlugin'](arg1);
}

export function DisconnectNetwork(arg1) {
  return window['go']['main']['App']['DisconnectNetwork'](arg1);
}

export function EnablePlugin(arg1) {
  return window['go']['main']['App']['EnablePlugin'](arg1);
}

export function GetChannelIDByName(arg1, arg2) {
  return window['go']['main']['App']['GetChannelIDByName'](arg1, arg2);
}

export function GetChannelInfo(arg1, arg2) {
  return window['go']['main']['App']['GetChannelInfo'](arg1, arg2);
}

export function GetChannels(arg1) {
  return window['go']['main']['App']['GetChannels'](arg1);
}

export function GetConnectionStatus(arg1) {
  return window['go']['main']['App']['GetConnectionStatus'](arg1);
}

export function GetMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3);
}

export function GetNetworks() {
  return window['go']['main']['App']['GetNetworks']();
}

export function GetServers(arg1) {
  return window['go']['main']['App']['GetServers'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LeaveChannel(arg1, arg2) {
  return window['go']['main']['App']['LeaveChannel'](arg1, arg2);
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function OnEvent(arg1) {
  return window['go']['main']['App']['OnEvent'](arg1);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function SaveNetwork(arg1) {
  return window['go']['main']['App']['SaveNetwork'](arg1);
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function ToggleChannelAutoJoin(arg1, arg2) {
  return window['go']['main']['App']['ToggleChannelAutoJoin'](arg1, arg2);
}

export function ToggleNetworkAutoConnect(arg1) {
  return window['go']['main']['App']['ToggleNetworkAutoConnect'](arg1);
}
