// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearPaneFocus(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClearPaneFocus'](arg1, arg2, arg3);
}

export function ConnectNetwork(arg1) {
  return window['go']['main']['App']['ConnectNetwork'](arg1);
}

export function DeleteNetwork(arg1) {
  return window['go']['main']['App']['DeleteNetwork'](arg1);
}

export function DisablePlugin(arg1) {
  return window['go']['main']['App']['DisablePlugin'](arg1);
}

export function DisconnectNetwork(arg1) {
  return window['go']['main']['App']['DisconnectNetwork'](arg1);
}

export function EnablePlugin(arg1) {
  return window['go']['main']['App']['EnablePlugin'](arg1);
}

export function GetChannelIDByName(arg1, arg2) {
  return window['go']['main']['App']['GetChannelIDByName'](arg1, arg2);
}

export function GetChannelInfo(arg1, arg2) {
  return window['go']['main']['App']['GetChannelInfo'](arg1, arg2);
}

export function GetChannels(arg1) {
  return window['go']['main']['App']['GetChannels'](arg1);
}

export function GetConnectionStatus(arg1) {
  return window['go']['main']['App']['GetConnectionStatus'](arg1);
}

export function GetJoinedChannels(arg1) {
  return window['go']['main']['App']['GetJoinedChannels'](arg1);
}

export function GetLastOpenPane() {
  return window['go']['main']['App']['GetLastOpenPane']();
}

export function GetMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3);
}

export function GetNetworks() {
  return window['go']['main']['App']['GetNetworks']();
}

export function GetNicknameColor(arg1, arg2) {
  return window['go']['main']['App']['GetNicknameColor'](arg1, arg2);
}

export function GetNicknameColorsBatch(arg1, arg2) {
  return window['go']['main']['App']['GetNicknameColorsBatch'](arg1, arg2);
}

export function GetOpenChannels(arg1) {
  return window['go']['main']['App']['GetOpenChannels'](arg1);
}

export function GetPluginConfig(arg1) {
  return window['go']['main']['App']['GetPluginConfig'](arg1);
}

export function GetPluginConfigSchema(arg1) {
  return window['go']['main']['App']['GetPluginConfigSchema'](arg1);
}

export function GetPrivateMessageConversations(arg1, arg2) {
  return window['go']['main']['App']['GetPrivateMessageConversations'](arg1, arg2);
}

export function GetPrivateMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPrivateMessages'](arg1, arg2, arg3);
}

export function GetServerCapabilities(arg1) {
  return window['go']['main']['App']['GetServerCapabilities'](arg1);
}

export function GetServers(arg1) {
  return window['go']['main']['App']['GetServers'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LeaveChannel(arg1, arg2) {
  return window['go']['main']['App']['LeaveChannel'](arg1, arg2);
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function OnEvent(arg1) {
  return window['go']['main']['App']['OnEvent'](arg1);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function OpenSettingsDisplay() {
  return window['go']['main']['App']['OpenSettingsDisplay']();
}

export function OpenSettingsNetworks() {
  return window['go']['main']['App']['OpenSettingsNetworks']();
}

export function OpenSettingsPlugins() {
  return window['go']['main']['App']['OpenSettingsPlugins']();
}

export function ReloadPlugin(arg1) {
  return window['go']['main']['App']['ReloadPlugin'](arg1);
}

export function SaveNetwork(arg1) {
  return window['go']['main']['App']['SaveNetwork'](arg1);
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetChannelOpen(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetChannelOpen'](arg1, arg2, arg3);
}

export function SetPaneFocus(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPaneFocus'](arg1, arg2, arg3);
}

export function SetPluginConfig(arg1, arg2) {
  return window['go']['main']['App']['SetPluginConfig'](arg1, arg2);
}

export function SetPrivateMessageOpen(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPrivateMessageOpen'](arg1, arg2, arg3);
}

export function ToggleChannelAutoJoin(arg1, arg2) {
  return window['go']['main']['App']['ToggleChannelAutoJoin'](arg1, arg2);
}

export function ToggleNetworkAutoConnect(arg1) {
  return window['go']['main']['App']['ToggleNetworkAutoConnect'](arg1);
}
