// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';
import {plugin} from '../models';
import {events} from '../models';

export function ConnectNetwork(arg1:main.NetworkConfig):Promise<void>;

export function DeleteNetwork(arg1:number):Promise<void>;

export function DisablePlugin(arg1:string):Promise<void>;

export function DisconnectNetwork(arg1:number):Promise<void>;

export function EnablePlugin(arg1:string):Promise<void>;

export function GetChannelIDByName(arg1:number,arg2:string):Promise<any>;

export function GetChannelInfo(arg1:number,arg2:string):Promise<main.ChannelInfo>;

export function GetChannels(arg1:number):Promise<Array<storage.Channel>>;

export function GetConnectionStatus(arg1:number):Promise<boolean>;

export function GetJoinedChannels(arg1:number):Promise<Array<storage.Channel>>;

export function GetMessages(arg1:number,arg2:any,arg3:number):Promise<Array<storage.Message>>;

export function GetNetworks():Promise<Array<storage.Network>>;

export function GetOpenChannels(arg1:number):Promise<Array<storage.Channel>>;

export function GetPrivateMessageConversations(arg1:number):Promise<Array<string>>;

export function GetPrivateMessages(arg1:number,arg2:string,arg3:number):Promise<Array<storage.Message>>;

export function GetServerCapabilities(arg1:number):Promise<main.ServerCapabilitiesInfo>;

export function GetServers(arg1:number):Promise<Array<storage.Server>>;

export function Greet(arg1:string):Promise<string>;

export function LeaveChannel(arg1:number,arg2:string):Promise<void>;

export function ListPlugins():Promise<Array<plugin.PluginInfo>>;

export function OnEvent(arg1:events.Event):Promise<void>;

export function OpenSettings():Promise<void>;

export function SaveNetwork(arg1:main.NetworkConfig):Promise<void>;

export function SendCommand(arg1:number,arg2:string):Promise<void>;

export function SendMessage(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SetChannelOpen(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function ToggleChannelAutoJoin(arg1:number,arg2:string):Promise<void>;

export function ToggleNetworkAutoConnect(arg1:number):Promise<void>;
